export const keypad = [
  { label: 'AC', tone: 'utility' },
  { label: '⌫', tone: 'utility' },
  { label: '%', tone: 'utility' },
  { label: '/', tone: 'operator' },
  { label: '7', tone: 'number' },
  { label: '8', tone: 'number' },
  { label: '9', tone: 'number' },
  { label: '*', tone: 'operator' },
  { label: '4', tone: 'number' },
  { label: '5', tone: 'number' },
  { label: '6', tone: 'number' },
  { label: '-', tone: 'operator' },
  { label: '1', tone: 'number' },
  { label: '2', tone: 'number' },
  { label: '3', tone: 'number' },
  { label: '+', tone: 'operator' },
  { label: '0', tone: 'number' },
  { label: '.', tone: 'number' },
  { label: '=', tone: 'equals' },
]
